In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]


numpy.ndarray

In [ ]:
# numpy 산술 연산
x = np.array([1.0, 2.0, 3.0])
y = np.array([4., 5., 6.])
print(x + y)
print(x - y)
print(x * y)
print(x / y)


[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]


In [4]:
x = np.array([1, 2, 3])
print(x / 2)

[0.5 1.  1.5]


In [ ]:
# numpy 다차원 배열
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [ ]:
# numpy 브로드캐스트
A = np.array([[1, 2], [3, 4]])
print(A * 3)
B = np.array([10, 20])
print(A + B)
print(A * B)

[[ 3  6]
 [ 9 12]]
[[11 22]
 [13 24]]
[[10 40]
 [30 80]]


In [ ]:
# numpy 원소 접근
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])
print(X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]
[51 14  0]


In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
for row in X:
    print(row)

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X = X.flatten()
print(X)

print(X[np.array([0, 2, 4])]) # 인덱스가 0, 2, 4인 원소 추출

In [10]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X = X.flatten()
print(X > 15) # 15보다 큰 원소를 추출
print(X[X > 15])

[ True  True False  True False False]
[51 55 19]
