In [1]:
import numpy as np

In [8]:
A = np.array([1, 2, 3, 4, 5])
print('A:\n', A)
print('A.ndim: ', A.ndim)
print('A.shape: ', A.shape)
print('A.dtype: ', A.dtype)
print()

B = np.array([[1, 2], [3, 4], [5, 6]])
print('B:\n', B)
print('B.ndim: ', B.ndim)
print('B.shape: ', B.shape)
print('B.dtype: ', B.dtype)



A:
 [1 2 3 4 5]
A.ndim:  1
A.shape:  (5,)
A.dtype:  int64

B:
 [[1 2]
 [3 4]
 [5 6]]
B.ndim:  2
B.shape:  (3, 2)
B.dtype:  int64


In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.dot(A, B)

# 행렬곱
# dim(a, b) * dim(c, d) = dim(a, d). 단 b == c여야함
# ex) dim(2, 3) * dim(3, 2) = dim(2, 2)

print('A.shape: ', A.shape)
print('A:\n', A, '\n')
print('B.shape: ', B.shape)
print('B:\n', B, '\n')
print('C.shape: ', C.shape)
print('C:\n', C, '\n')

A.shape:  (2, 3)
A:
 [[1 2 3]
 [4 5 6]] 

B.shape:  (3, 2)
B:
 [[1 2]
 [3 4]
 [5 6]] 

C.shape:  (2, 2)
C:
 [[22 28]
 [49 64]] 

