In [2]:
import torch
# if torch.cuda.is_available():
#     print('use CUDA')
#     torch.cuda.device(0)

print("# 텐서 생성")
print(torch.tensor([[1, 2], [3, 4]])) # 2차원 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], device='cuda:0')) # GPU 사용
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)) # 데이터 타입 지정


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:

print("# 텐서 변환")
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy()) # ndarray로 변환
temp = torch.tensor([[1, 2], [3, 4]], device='cuda:0')
print(temp.to('cpu').numpy()) # device 변환 후 ndarray로 변환

temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7]) # 1차원 벡터 생성
print(temp)
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

In [ ]:
print("# 텐서 연산")
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

In [ ]:
print("# 텐서 차원 변환")
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.shape)
print(temp.view(4, 1)) # 2x2 -> 4x1
print(temp.view(-1)) # 2x2 -> 4
print(temp.view(1, -1)) # 2x2 -> 1x? -> 1x4
print(temp.view(-1, 1)) # 2x2 -> ?x1 -> 4x1